### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by FlyersPh9** [ArtCC/OctoPrint-Siri-RPi#2]
Hello,

I just followed the guide to setup and ran into a couple of issues / areas that could be a little more clear.

1. I wasn't sure where to place the unzipped folder onto the Raspberry Pi.  I ended up placing the folder within the root directory which Filezilla placed me into.  This required me to enter `cd OctoPrint-Siri-RPi` prior to running `./start.sh`. 
2. After running `./start.sh` within Terminal on my macOS, the script runs but when trying to close the terminal window it wants to stop running my script.  I'm sure there is a way to fix this, but I have not discovered how to yet.
3. The Siri Shortcuts section has a link that says Download Shortcuts examples with captures.  It says "Add these shortcuts by opening the link on your iOS or iPadOS device where you have installed the Shortcuts application".  The link goes to a ZIP which requires additional software on iOS to unpack.  Could you maybe share the shortcuts rather than take screenshots?

I'm really excited to get this running, but right now I am stuck on step 3 trying to replicate your scripts into English. Thank you for your hard work!

**Comment by artcc** [comment]
Hi!
The problem is that I stopped having a 3D printer, so I put captures of the shortcuts.
As for the terminal, if you access via ssh to your Raspberry, you can close the terminal and the NodeJS session in your OctoPrint will remain in use. It's a theme I wanted to improve, adding plugo to Octoprint but as I said, I stopped having a printer...
Regards,

Arturo.
